
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

export default function TermsAndConditionsPage() {
    return (
        <div className="container mx-auto px-4 py-12 md:py-16">
            <Card className="max-w-4xl mx-auto">
                <CardHeader>
                    <CardTitle className="font-headline text-3xl">Terms and Conditions</CardTitle>
                    <CardDescription>Last updated: July 8, 2024</CardDescription>
                </CardHeader>
                <CardContent className="prose prose-sm md:prose-base dark:prose-invert max-w-none">
                    <p>Welcome to VisaFor ("the Platform"). These Terms and Conditions govern your use of the VisaFor CRM system. By registering for an account, you agree to be bound by these terms.</p>
                    
                    <h3>1. Professional Responsibility (For Lawyers & Legal Professionals)</h3>
                    <p>As a regulated legal professional using this Platform, you acknowledge and agree to the following:</p>
                    <ul>
                        <li><strong>Final Authority:</strong> You are the final authority on all legal advice, document submissions, and strategic decisions for your clients.</li>
                        <li><strong>AI as an Assistant:</strong> The Platform's AI tools (including but not limited to the Application Checker, Document Summarizer, and message composer) are provided as assistive technology. They are intended to augment, not replace, your professional judgment.</li>
                        <li><strong>Verification Required:</strong> You are solely responsible for verifying the accuracy, completeness, and appropriateness of any information, document, or suggestion generated by the AI before using it or sharing it with a client.</li>
                        <li><strong>Compliance:</strong> You are responsible for ensuring your use of the Platform complies with all rules and regulations set forth by your governing body (e.g., Law Society, CICC).</li>
                    </ul>

                    <h3>2. Disclaimers Regarding AI-Generated Content</h3>
                    <p>The Platform utilizes artificial intelligence to provide suggestions, summaries, and automated content. You understand and accept that:</p>
                    <ul>
                        <li>AI-generated content may contain inaccuracies, errors, or omissions.</li>
                        <li>AI tools are not a substitute for legal research, professional expertise, or independent verification.</li>
                        <li>VisaFor Inc. is not liable for any errors, damages, or professional consequences arising from your reliance on AI-generated content without proper professional review.</li>
                    </ul>

                    <h3>3. Account Security</h3>
                    <p>You are responsible for maintaining the confidentiality of your account password and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.</p>

                    <h3>4. User Conduct</h3>
                    <p>You agree not to use the Platform for any unlawful purpose or to engage in any conduct that could damage, disable, or overburden the Platform. You are solely responsible for all data and content you upload or input into the system.</p>

                     <h3>5. Subscription and Payments</h3>
                    <p>Fees for our services are described on our pricing page. By choosing a subscription plan, you agree to pay all applicable fees. Subscriptions will automatically renew unless canceled. All payments are non-refundable.</p>

                    <h3>6. Termination</h3>
                    <p>We may terminate or suspend your access to the Platform at any time, without prior notice or liability, for any reason, including if you breach these Terms.</p>

                    <h3>7. Changes to Terms</h3>
                    <p>We reserve the right to modify these terms at any time. We will notify you of any changes by posting the new terms on this page. Your continued use of the Platform after any such change constitutes your acceptance of the new Terms and Conditions.</p>
                </CardContent>
            </Card>
        </div>
    );
}
